name: Deploy

on:
  release:
    types:
      - created

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Check out git repository
        uses: actions/checkout@v1

      - name: Install Node.js and yarn
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Install dependencies
        run: yarn --prod

      - name: Build app
        run: yarn build

      - name: Deploy
        uses: crazy-max/ghaction-github-pages@v1
        with:
          build_dir: build
          committer_email: 764798966@qq.com
          fqdn: user.n.apisium.cn
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload to cos
        uses: ShirasawaSama/cos-action@0.0.0
        with:
          secret_id: ${{ secrets.TENCENT_CLOUD_SECRET_ID }}
          secret_key: ${{ secrets.TENCENT_CLOUD_SECRET_KEY }}
          cos_bucket: ${{ secrets.COS_BUCKET }}
          cos_region: ${{ secrets.COS_REGION }}
          local_path: build
          accelerate: true
          clean: true
